language: node_js
dist: trusty
node_js:
  - 7.4
sudo: required
addons:
    code_climate:
        repo_token: 3b68f162f31837cfe10190fda5667892e8823183d2f7844d44028d0f74f258ab
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install codecov  
script:
  - npm run ng test -- --single-run=true --browsers Chrome --code-coverage
  - ./node_modules/codecov/bin/codecov
  - npm run ng lint
  - npm run ng build